module.exports = {
  content: [
    "./_layouts/**/*.html",
    "./_includes/**/*.html",
    "./_pages/**/*.md",
    "./*.md",
    "./*.html",
    "./assets/css/**/*.scss",
  ],
  theme: {
    fontSize: {
      xs: ["0.875rem", { lineHeight: "1.25", letterSpacing: "0.06em" }],
      sm: ["1.25rem", { lineHeight: "1.6", letterSpacing: "0.06em" }],
      md: ["1.5rem", { lineHeight: "32px", letterSpacing: "0.02em" }],
      lg: ["2rem", { lineHeight: "1.4", letterSpacing: "0.02em" }],
      xl: ["2.5rem", { lineHeight: "48.48px" }],
      "2xl": ["3rem", { lineHeight: "60.48px" }],
      "3xl": ["4rem", { lineHeight: "80.48px" }],
      "4xl": ["5rem", { lineHeight: "100.48px" }],
      "5xl": ["6rem", { lineHeight: "120.48px" }],
      "6xl": ["7rem", { lineHeight: "140.48px" }],
      heading: ["2.5rem", { lineHeight: "48.48px" }],
      body: ["2.5rem", { lineHeight: "37.68px", letterSpacing: "0.02em" }],
      "body-bold": [
        "1.5rem",
        { lineHeight: "37.92px", letterSpacing: "0.02em" },
      ],
    },
    fontFamily: {
      sans: ["AkzidGro", "Helvetica", "Arial", "ui-sans-serif", "system-ui"],
      serif: ["Georgia", "ui-serif"],
      mono: ["DM Mono", "SFMono-Regular", "monospace"],
      display: [
        "AkzidGro",
        "Helvetica Neue",
        "Helvetica",
        "Arial",
        "ui-sans-serif",
        "system-ui",
      ],
      body: [
        "AkzidGro",
        "Helvetica Neue",
        "Helvetica",
        "Arial",
        "ui-sans-serif",
        "system-ui",
      ],
    },
    fontWeight: {
      light: 300,
      normal: 400,
      medium: 500,
      bold: 700,
      super: 900,
    },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
      "body-regular": "0.157em",
      "body-bold": "0.158em",
      caption: "0.171em",
      "body-regular-mobile": "0.158em",
      "body-bold-mobile": "0.158em",
      "caption-mobile": "0.171em",
    },
    extend: {
      width: {
        card: "160px",
        "card-lg": "240px",
        mobile: "320px",
        "mobile-lg": "480px",
        tablet: "640px",
        "tablet-lg": "880px",
        desktop: "1024px",
        "desktop-lg": "1256px",
        widescreen: "1400px",
      },
      screens: {
        card: "160px",
        "card-lg": "240px",
        mobile: "320px",
        "mobile-lg": "480px",
        tablet: "640px",
        "tablet-lg": "880px",
        desktop: "1024px",
        "desktop-lg": "1256px",
        widescreen: "1400px",
      },
      scale: {
        80: "0.8",
        60: "0.6",
        40: "0.4",
        30: "0.3",
      },
    },
  },
  variants: {
    scale: ["responsive"],
  },
  plugins: [],
};
