name: Deploy Jekyll with TailwindCSS

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM deps
        run: npm ci

      - name: Install Jekyll deps
        run: |
          gem install bundler
          bundle install

      - name: Compile SCSS to CSS
        run: npx sass ./_assets/css/tailwind.scss ./assets/css/tailwind.css

      - name: Build Tailwind CSS
        run: |
          npx tailwindcss -i ./assets/css/tailwind.css -o ./assets/css/main.css --minify

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
